name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install and Build Observable Framework
        working-directory: observable-framework
        run: |
          echo "Installing dependencies for Observable Framework..."
          npm ci
          echo "Building Observable Framework static site..."
          npm run build

      - name: Copy Observable build to Docusaurus static dir
        run: |
          echo "Copying dashboard files..."
          # Create the target directory inside the Docusaurus static folder
          mkdir -p static/performance-chart
          # Copy the contents of the Observable build output to the new directory
          cp -r observable-framework/dist/* static/performance-chart/

      - name: Install Docusaurus dependencies
        run: npm ci

      - name: Build Docusaurus website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This is the Docusaurus build output directory.
          publish_dir: ./build